### PR TITLE
Consistently use decimal file units

### PR DESCRIPTION
**Pull request by da2x**
Right now the File Info dialog uses decimal units (like the rest of the OS), and every other view in the app uses binary units. This pull request changes it so that the app uses decimal units (like the rest of the OS) everywhere.

### CODE REVIEW

**Comment by 1488777** [comment]
Ii

**Comment by BigJDoveBaby** [comment]
Pull up please

**Comment by Grossdm** [comment]
While @da2x may have a point about Android's use of decimal data units, I rarely encounter this in my device usage.

I checked and confirmed that both Root Explorer and [Total Commander](http://www.ghisler.com/android.htm) use binary data units. They do not go to the extent of displaying the units as binary **explicitly**, e.g. MiB, GiB, etc.

Perhaps there should be more review or discussion about this PR.

**Comment by javiergm1983** [comment]
Hi, first of all thank you for your pull request and sorry for the very late response, but better late than never :smiley: 

We have to keep using binary units because we adopted that standard in all our clients long time ago for several reasons and we have to preserve homogeneity among all of them (Android, iOS, UWP, MEGAsync, web client, etc.). For that reason, if we decide move to use decimal units we should do it in all clients. We will take it into account and consider that in the future.

I encourage you to colaborate again if detect something that could be improved. Thanks.

**Pull request closed without merging**
